# SPDX-FileCopyrightText: Copyright © 2026 ReallyMe LLC. All rights reserved
#
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "identity-presentation-delivery-siop-verifier"
version = "0.2.0"
edition = "2021"
publish = false
license = "MIT OR Apache-2.0"

[features]
default = []

native = ["envelopes-jwk/native", "envelopes-jwt/native"]
wasm   = ["envelopes-jwk/wasm", "envelopes-jwt/wasm"]

[dependencies]
identity-presentation-delivery-siop-core = { version = "0.2.0", path = "../core" }
reallyme-ssi-proto = { workspace = true }
envelopes-jwt = { workspace = true }
envelopes-jwk = { package = "reallyme-crypto-jwk", version = "=0.3.9", default-features = false }
codec-base64url = { package = "reallyme-codec-base64url", version = "=0.2.3" }
reallyme-crypto = { workspace = true, features = ["constant-time", "sha2"] }
thiserror = { workspace = true }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
zeroize = { workspace = true, features = ["derive"] }

[dev-dependencies]
crypto-core = { package = "reallyme-crypto-core", version = "=0.3.9" }
crypto-dispatch = { package = "reallyme-crypto-dispatch", version = "=0.3.9", features = ["native"] }
[lints]
workspace = true
