// SPDX-FileCopyrightText: Copyright © 2026 ReallyMe LLC. All rights reserved
//
// SPDX-License-Identifier: MIT OR Apache-2.0

use std::os::raw::{c_char, c_int, c_uchar};

// SAFETY: This is the complete raw FFI surface for the local C shim generated by
// the build script. Callers must pass valid borrowed pointers and lengths; the
// safe wrapper in `identity-trust-tsl-xmlsec` enforces that contract.
#[allow(unsafe_code)]
extern "C" {
    /// Verify an ETSI TSL/LOTL XML document with the generated libxmlsec C shim.
    ///
    /// Pointer and length contract (the shim re-validates each item and returns
    /// [`crate::MEID_XMLSEC_STATUS_INVALID_ARGUMENT`] on violation):
    ///
    /// - `xml` points to `xml_len` readable bytes, with
    ///   `1 <= xml_len <= MEID_XMLSEC_MAX_XML_BYTES`.
    /// - `trusted_roots_der` and `trusted_roots_der_lens` each point to
    ///   `trusted_roots_count` readable elements, with
    ///   `1 <= trusted_roots_count <= MEID_XMLSEC_MAX_TRUSTED_ROOTS`. Element
    ///   `i` of `trusted_roots_der` points to `trusted_roots_der_lens[i]`
    ///   readable bytes of one DER certificate, with
    ///   `1 <= len <= MEID_XMLSEC_MAX_TRUSTED_ROOT_DER_BYTES`.
    /// - `signer_der` points to `signer_der_capacity` writable bytes, with
    ///   `1 <= signer_der_capacity <= MEID_XMLSEC_MAX_SIGNER_DER_BYTES`, and
    ///   must not overlap any input buffer or `signer_der_len`.
    /// - `signer_der_len` points to one writable `usize`.
    ///
    /// All input buffers are borrowed for the duration of the call only and
    /// are never written, retained, or freed by the shim. The signed 64-bit
    /// Unix time is used for RFC 5280 certificate validation. On success, the
    /// function copies the exact certificate selected by xmlsec into
    /// `signer_der` and stores its length in `signer_der_len`.
    ///
    /// Process-wide library initialization runs exactly once, guarded by
    /// `pthread_once`; its status is recorded and returned unchanged to every
    /// later call.
    #[allow(clippy::too_many_arguments)]
    pub fn meid_xmlsec_verify_tsl(
        xml: *const c_char,
        xml_len: usize,
        trusted_roots_der: *const *const c_uchar,
        trusted_roots_der_lens: *const usize,
        trusted_roots_count: usize,
        verification_time_unix: i64,
        allow_trusted_leaf: c_int,
        signer_der: *mut c_uchar,
        signer_der_capacity: usize,
        signer_der_len: *mut usize,
    ) -> c_int;
}
