// SPDX-FileCopyrightText: Copyright © 2026 ReallyMe LLC. All rights reserved
//
// SPDX-License-Identifier: MIT OR Apache-2.0

use std::os::raw::{c_char, c_int, c_uchar};

// SAFETY: This is the complete raw FFI surface for the local C shim generated by
// the build script. Callers must pass valid borrowed pointers and lengths; the
// safe wrapper in `identity-trust-tsl-xmlsec` enforces that contract.
#[allow(unsafe_code)]
extern "C" {
    /// Verify an ETSI TSL/LOTL XML document with the generated libxmlsec C shim.
    ///
    /// The caller must provide a non-null pointer to `xml_len` bytes of XML and
    /// a non-null, NUL-terminated trusted certificate PEM path. The signed
    /// 64-bit Unix time is used for RFC 5280 certificate validation. The function
    /// `signer_der` must point to `signer_der_capacity` writable bytes and
    /// `signer_der_len` must be writable. On success, the function copies the
    /// exact certificate selected by xmlsec into that buffer and reports its
    /// length. It does not retain any pointer after returning.
    pub fn meid_xmlsec_verify_tsl(
        xml: *const c_char,
        xml_len: usize,
        trusted_pem_path: *const c_char,
        verification_time_unix: i64,
        allow_trusted_leaf: c_int,
        signer_der: *mut c_uchar,
        signer_der_capacity: usize,
        signer_der_len: *mut usize,
    ) -> c_int;
}
