# SPDX-FileCopyrightText: Copyright © 2026 ReallyMe LLC. All rights reserved
#
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "reallyme-did-method-web"
version = "0.3.1"
description = "did:web identifier generation, validation, and HTTPS location mapping."
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[features]
default = ["native"]
native = ["reallyme-did-method-jwk/native"]
wasm = ["reallyme-did-method-jwk/wasm"]

[dependencies]
identity-core-primitives = { workspace = true }
percent-encoding = { workspace = true }
reallyme-codec = { workspace = true, features = ["multikey"] }
reallyme-did-method-jwk = { path = "../jwk", version = "0.3.1", default-features = false }
reallyme-did-method-key = { path = "../key", version = "0.3.1", default-features = false }
reallyme-ssi-proto = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }
zeroize = { workspace = true }

[lints]
workspace = true
