# SPDX-FileCopyrightText: Copyright © 2026 ReallyMe LLC. All rights reserved
#
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "identity-presentation-delivery-contact-validator"
version = "0.2.0"
edition = "2021"
publish = false
license = "MIT OR Apache-2.0"

[features]
default = []

[dependencies]
identity-presentation-delivery-contact-core = { version = "0.2.0", path = "../core" }
reallyme-ssi-proto = { workspace = true }
thiserror = { workspace = true }
zeroize = { workspace = true, features = ["derive"] }
[lints]
workspace = true
