# SPDX-FileCopyrightText: Copyright © 2026 ReallyMe LLC. All rights reserved
#
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "reallyme-did-method-jwk"
version = "0.2.0"
description = "did:jwk deterministic identifier helpers."
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
identity-core-primitives = { workspace = true }
reallyme-codec = { workspace = true, features = ["base64url"] }
reallyme-ssi-proto = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
