# SPDX-FileCopyrightText: Copyright © 2026 ReallyMe LLC. All rights reserved
#
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "reallyme-did-method-ebsi"
version = "0.4.0"
description = "did:ebsi versioned base58btc identifier helpers."
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[features]
default = ["native"]
native = ["reallyme-did-method-jwk/native"]
wasm = ["reallyme-did-method-jwk/wasm"]

[dependencies]
identity-core-primitives = { workspace = true }
reallyme-did-method-jwk = { path = "../jwk", version = "0.4.0", default-features = false }
reallyme-ssi-proto = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true, features = ["parsing"] }
url = { workspace = true }
zeroize = { workspace = true }

[dev-dependencies]
reallyme-codec = { workspace = true, features = ["base64url"] }

[lints]
workspace = true
